version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv_files:/csv_files  # Mount csv_files folder to access CSV files
    ports:
      - "5432:5432"

  data_loader:
    image: postgres:latest
    depends_on:
      - db
    volumes:
      - ./csv_files:/csv_files
      - ./load_data.sh:/load_data.sh
    entrypoint: /bin/bash /load_data.sh
    environment:
      PGPASSWORD: admin
    links:
      - db
